#!/usr/bin/env bash

set -e

export DOTFILES_PROFILE="${DOTFILES_PROFILE:-personal}"
case "$DOTFILES_PROFILE" in
    work|personal) ;;
    *) echo 'DOTFILES_PROFILE must be work or personal' >&2; exit 1 ;;
esac

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
