[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
leftshift = leftshift
rightshift = rightshift
rightcontrol = rightcontrol
# lctrl = oneshot(lctrl)
# rctrl =  oneshot(rctrl)
# lalt = oneshot(alt)
# ralt = oneshot(altgr)

[alt]
j=down
k=up
h=left
l=right
