[mgr]
sort_by = "extension"
sort_sensitive = false
sort_dir_first = true
linemode = "mtime"
show_symlink = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = "nvim %*", block = true, for = "windows" },
]
